### ISSUE TITLE
subresource app creation doesn't consider attributes parameter in payload while creating the app

### ISSUE THREAD

**Issue by rupam-rai** [apigee/edge-launchpad#8]
In the below example attributes are ignored while app creation.
`'{"name":"AISP_App_v2","attributes":[{"name":"tppId","value":"12345"}]}'`

**Comment by kidiyoor** [comment]
This is because apigeetool ignores the attribute property during app creation. I created a issue in apigeetool here - [issue76](https://github.com/apigee/apigeetool-node/issues/76)

**Comment by kidiyoor** [comment]
Fixed at apigeetool in PR - https://github.com/apigee/apigeetool-node/pull/78
